x = input()
print(x)
text = input()
print(text)
name = input('Enter your name: ')
print('Hello, ' + name)
name = input('What is your name? ')
age = int(input())
print(age)
x = '2'
y = '4'
z = int(x) + int(y)
print(z)
name = input()
age = input()
print(name + 'is' + age)
x = int(input())
y = int(input())
print(x + y)