n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
print(f'A soma de {n1} e {n2} é: {n1 + n2}')
print(f'A subtrração de {n1} e {n2} é: {n1 - n2}')
print(f'A multiplicação de {n1} e {n2} é: {n1 * n2}')
print(f'A divisão de {n1} e {n2} é: {n1 / n2}')